Better warning behavior wöhler analyzer
boschresearch/pylife pull request #102
Opened 2024-07-25 08:46 UTC by old2rng

Update warning behaviour for Wöhler curve analyzer methods #66 
Hint: Change of some warnings possible do to further issues #101

2024-07-30 11:55 UTC, johannes-mueller requested changes
Thanks. See my remarks about the code below.

2024-07-30 11:55 UTC, johannes-mueller commented on src/pylife/materialdata/woehler/maxlike.py
> +                # confirm with AMP4-Lab (do they evaluate maxli without any runouts)
Please remove this comment. Consider doing what it says, first.

2024-07-30 11:55 UTC, johannes-mueller commented on src/pylife/materialdata/woehler/probit.py
> +            warnings.warn(UserWarning("Probit needs at least two, preferable mixed, load levels in the infinite zone. Falling back to Elementary."))
```suggestion
            warnings.warn(UserWarning("Probit needs at least two – preferably mixed – load levels in the infinite zone. Falling back to Elementary."))
```

2024-07-30 11:55 UTC, johannes-mueller commented on tests/materialdata/woehler/test_analyzer.py
> +    with pytest.warns(UserWarning, match=r"Probit needs at least two, preferable mixed, load levels in the infinite zone. Falling back to Elementary."):
```suggestion
    with pytest.warns(UserWarning, match=r"Probit needs at least two – preferably mixed – load levels in the infinite zone. Falling back to Elementary."):
```

2024-07-30 11:55 UTC, johannes-mueller commented on src/pylife/materialdata/woehler/elementary.py
> +              raise ValueError("Need at least two different load levels in the finite zone to do a Wöhler slope analysis.")
Bad indentation

```suggestion
        if len(self._fd.load.unique()) < 2 or len(self._fd.finite_zone.load.unique()) < 2:
            raise ValueError("Need at least two different load levels in the finite zone to do a Wöhler slope analysis.")
```

2024-07-30 11:55 UTC, johannes-mueller commented on src/pylife/materialdata/woehler/maxlike.py
> +                raise ValueError("MaxLikeHood: need at least three fractures on two load levels.")
Why do these `_infinite_*` have to be class members? Can't we just forget them when we are done.

```suggestion
    def __max_likelihood_inf_limit(self):

        infinite_fractures = self._fd.infinite_zone.loc[self._fd.infinite_zone.fracture]
        infinite_runouts = self._fd.infinite_zone.loc[~self._fd.infinite_zone.fracture]
        infinite_fractured_loads = np.unique(infinite_fractures.load.values)
        infinite_runout_loads = np.unique(infinite_runouts.load.values)
        infinite_mixed_loads = np.intersect1d(infinite_runout_loads, infinite_fractured_loads)

        def fail_if_less_than_two_mixed_levels():
            if len(infinite_mixed_loads) < 2:
                raise ValueError("MaxLikeHood: need at least two mixed load levels.")

        def fail_if_less_than_three_fractures():
            if infinite_fractures.shape[0] < 3 or len(infinite_fractured_loads) < 2:
                raise ValueError("MaxLikeHood: need at least three fractures on two load levels.")

```

2024-07-31 07:33 UTC, old2rng commented on src/pylife/materialdata/woehler/maxlike.py
> +                # confirm with AMP4-Lab (do they evaluate maxli without any runouts)
Thanks for your hint. I will check the comment and update code if necessary.

2024-07-31 07:37 UTC, old2rng commented on src/pylife/materialdata/woehler/maxlike.py
> +                raise ValueError("MaxLikeHood: need at least three fractures on two load levels.")
Yes, you are right. They don't need to be classed. Thanks for your suggestion!

2024-08-01 12:16 UTC, johannes-mueller approved these changes
LGTM

2024-08-01 12:17 UTC, merged