Fkm nonlinear
boschresearch/pylife pull request #29
Opened 2023-09-05 14:35 UTC by maierbn

2023-09-05 14:37 UTC, maierbn commented on src/pylife/mesh/gradient.py
> +        print(df.index.shape)
- [ ] Remove `print` statements

2023-09-05 14:38 UTC, maierbn commented
- [ ] `process` in `general.py` Revert to previous signature without the flush parameter, move parameter to `fkm_nonlinear.py`
- [ ] Document classes and/or modules with sphinx

2023-09-06 17:29 UTC, maierbn commented
@johannes-mueller I cannot push to the fkm_nonlinear branch, do I have all required access rights?

2023-09-18 16:26 UTC, johannes-mueller requested changes
Thanks @maierbn – this is a lot of good work.

While I see some room for improvement, we should merge it soon to release it as beta to get feedback from users. Then we can rework stuff in smaller steps.

Can you please go through my comments and look if you can apply them.

Thanks

2023-09-18 16:26 UTC, johannes-mueller commented on demos/fkm_nonlinear/fkm_nonlinear_full.ipynb
Please clean the ipynb files and remove the output. Output in ipynb files usually leads to horrible merge conflicts.

2023-09-18 16:26 UTC, johannes-mueller commented on docs/demos/import_mesh_abaqus.nblink
The abaqus demo cannot be part of the docs as readthedocs.io does not have Abaqus avaliable. Not sure about ANSYS.

2023-09-18 16:26 UTC, johannes-mueller commented on docs/tutorials/fkm_nonlinear.rst
Please link those tutorials in `docs/tutorials.rst`.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +    @K_p.setter
Do we really need the setters? I think it would be in general be a good thing to discourage modifying data structures as that can lead to side effects.

2023-09-18 16:26 UTC, johannes-mueller commented on docs/materiallaws/notch_approximation_laws.rst
> +The notch approximation law classes ̀ `ExtendedNeuber``, ``SeegerBeste``, and ``Binned``
Please don't reference the classes in the page title. This leads to a two lined page title.

If needed write a small paragraph to shortly introduce the classes and link to them there. Maybe also a dedicated page per class and a smaller module introduction page would be an option.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +        '''Get Young's Modulus'''
Please drop the "Get" if it's a property.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +        '''Get the shape factor (de: Traglastformzahl)'''
This is rendering strangely

2023-09-18 16:26 UTC, johannes-mueller commented on docs/cookbook.rst
> +   demos/surface_layer_roughness_explain.nblink
Where do these link to? There are no file `demos/surface_layer_roughness_*.nblink`.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +    def stress(self, load, rtol=1e-4, tol=1e-4):
Please force the use of keywords for the optional parameters.

```suggestion
    def stress(self, load, *, rtol=1e-4, tol=1e-4):
```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +
Please consider either documenting `rtol` and `tol` or maybe to use instead a general `**kwargs` argument that is passed through to `optimize.newton()`

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +    def load(self, stress, rtol=1e-4, tol=1e-4):
Same remarks about `rtol` and `tol` as in `.stress()`. Same for all the other methods with `rtol` and `tol` arguments.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +        if type(self._maximum_absolute_load) == pd.core.frame.DataFrame:
Prefer `isinstance()` over `type()`

```suggestion
        if isinstance(self._maximum_absolute_load, pd.DataFrame):
```
See https://switowski.com/blog/type-vs-isinstance/

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +
Please drop these blank lines (also the one in `__init__`)

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +    def _create_bins_single_assessment_point(self):
Let's see if we can drop duplicated code here.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +    def _create_bins(self):
Please put private methods to the end of classes.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +        if type(load) == pd.core.frame.DataFrame and isinstance(self._lut_primary_branch.index, pd.MultiIndex):
Please use `isinstance()`

In general we should discuss after the merge if we can simplify this.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +class Binned:
This class has some duplicated code and some `if ... elif ... else` clauses which we should try to simplify. We will do that after the merge in a separated smaller issue

- [x] Please file an issue after the merge about this.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law_base.py
> +    @K_p.setter
Do we really need the setters?

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law_seegerbeste.py
> +    Remarks/ Bug issues from 25.03.2022 (CR/AMP4-Bucher):
Please drop the name reference

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law_seegerbeste.py
> +            used, which is a bit slower but arrives at a correct solution.
Are these issues that we can fix from within pyLife? 

- [x] If so please file those issues after the merge.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law_seegerbeste.py
> +        if type(load) is not float:
Again: consider `np.asarray()` also in all the other places.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law_seegerbeste.py
> +    def stress(self, load, rtol=1e-4, tol=1e-4):
```suggestion
    def stress(self, load, *, rtol=1e-4, tol=1e-4):
```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law_seegerbeste.py
> +        if hasattr(delta_stress[1], "iloc") and sum(delta_stress[1]) < len(delta_stress[1]):
Do we really need to check for the attribute. `delta_stress` is a local variable, so we have control of its type here. Maybe again something for `np.asarray()`?

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law_seegerbeste.py
> +            delta_stress = optimize.newton(func=self._stress_secondary_implicit, x0=x0, \
`numpy.optimize.newton()` returns a several values So it might be a good idea to also catch those in distinct variables for readability.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/mesh/gradient.py
> +    '''Computes the gradient of a value in a 3D mesh that was imported from Ansys or Abaqus.
Please drop the reference to Ansys and Abaqus. It should work on any `Meshsignal`.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/mesh/gradient.py
> +                return 1 if j == 2 else 0
```suggestion
            if a == 0:
                return -1
            return 1 if j == a - 1 else 0
```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +        factor = np.divide(load, stress, out=np.ones_like(load), where=stress!=0)
Maybe you can use `np.asarray()` here.

```suggestion
        factor = np.divide(np.asarray(load), stress, out=np.ones_like(load), where=stress!=0)
```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +
Here seems something flipped with `K` and `K_prime`.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +        factor = np.divide(delta_load, delta_stress, out=np.ones_like(delta_load), where=delta_stress!=0)
```suggestion
        factor = np.divide(np.asarray(delta_load), delta_stress, out=np.ones_like(delta_load), where=delta_stress!=0)
```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +            args=([load]), rtol=rtol, tol=tol, maxiter=20)
```suggestion
        stress = optimize.newton(
            func=self._stress_secondary_implicit, 
            x0=delta_load,
            fprime=self._d_stress_secondary_implicit, 
            args=([delta_load]),
            rtol=rtol, tol=tol, maxiter=20 
        )
```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/mesh/gradient.py
> +class Gradient3D(Mesh):
Tasks for after the merge
- [ ] Performance profiling
- [ ] Performance comparison with `Gradient`
- [ ] If needed performance optimization in `Gradient3D`

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/mesh/surface.py
Is this needed or can it be done simply knowing the nodes that are at the surface beforehand? Maybe we can drop it for now and add it in a separate PR if we need it.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/damage_parameter.py
> +    def __init__(self, collective, assessment_parameters):
The docstrings for `__init__()`  needs to be at class level.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/damage_parameter.py
> +        self._collective["k"] = 0
Modifying `self_collective` means that the `collective` object handed in as argument in `__init__` is modified as a side effect. This should be avoided.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/damage_parameter.py
> +    def collective(self):
Consider implementing this as function rather than as class.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/damage_parameter.py
> +            self._P_RAJ_D_0.reset_index(drop=True, inplace=True)
Maybe `np.asarray()` again.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/damage_parameter.py
> +class P_RAJ:
Same remarks as for `P_RAM`

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/damage_parameter.py
> +                #print(f"optimize S_max: {row.S_max}, epsilon_max: {row.epsilon_max}, epsilon_open: {row.epsilon_open}")
Please remove the debug comment

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_load_distribution.py
> +            raise ValueError(f"P_A={input_parameters.P_A} has to be one of "+"{1e-7, 1e-6, 1e-5, 7.2e-5, 1e-3, 2.3e-1, 0.5}.")
Consider looping over a list of tuples instead of the `if ... elif` cacade

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_load_distribution.py
> +                result.iloc[:,0] = result.iloc[:,0] * gamma_L
Sure it is only the first column? Indexing columns using `iloc` usually leads to trouble.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_load_distribution.py
> +        if type(self._obj) == pd.core.series.Series:
Use `isinstance()`

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/constants.py
> +
Please remove those headers and replace with the standard copyright header.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/constants.py
> +def get_constants_for_material_group(assessment_parameters):
Please drop the `get_` prefix. We generally don't use those.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/constants.py
> +def _set_f_25percent(assessment_parameters, resulting_constants):
The argument `assessment_parameters` seems unused. Consider making this function inline.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/damage_calculator.py
> +
Please remove those

2023-09-18 16:26 UTC, johannes-mueller commented on .gitattributes
We need to look for a better solutions on how to clean the notebooks. Setting up an issue #31

2023-09-18 16:26 UTC, johannes-mueller commented on demos/fkm_nonlinear/fkm_nonlinear.ipynb
Please remove the output from all notebooks.

2023-09-18 16:26 UTC, johannes-mueller commented on docs/strength/fkm_nonlinear.rst
> +##################################################################
Please adjust the length of the `###` line to match with the title. Sphinx will likely complain. Maybe we should think of some way of automating this. Is there such a functionality in VSCode. Emacs has something.

2023-09-18 16:26 UTC, johannes-mueller commented on docs/strength/fkm_nonlinear_damage_calculator.rst
> +The ``DamageCalculatorPRAM``, ``DamageCalculatorPRAJ``, and ``DamageCalculatorPRAJMinerElementary`` classes
Don't put the class names into the title.

Suggestion: Shortly present the classes in the model description and then the classes get their own docs page.

2023-09-18 16:26 UTC, johannes-mueller commented on docs/tutorials/import_meshes.rst
> +* :doc:`ANSYS *.rst files <demos/import_mesh_ansys>`
Maybe we can't show those in the docs.

2023-09-18 16:26 UTC, johannes-mueller commented on tools/odbclient/src/odbclient/odbclient.py
Can this change be dropped? It does not belong into this branch IMO.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +"""
Please put in the correct header

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +def calculate_cyclic_assessment_parameters(assessment_parameters_):
Consider dropping the `calculate_` prefix for all the names. Prefixes often add more noise than information.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +RM_OR_HV_REQUIRED_ERROR = RuntimeError("R_m required")
Shouldn't this be a `ValueError` and a bit more vebose messsage?

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +        raise RM_OR_HV_REQUIRED_ERROR
```suggestion
    if "R_m" not in assessment_parameters:
        raise RM_OR_HV_REQUIRED_ERROR 

    # compute K' according to eq. (2.5-13)
    assessment_parameters["K_prime"] = constants.a_sigma * assessment_parameters.R_m ** constants.b_sigma \
        / (np.minimum(constants.epsilon_grenz, constants.a_epsilon * assessment_parameters.R_m ** constants.b_epsilon)) \
            ** constants.n_prime       
```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +        raise RM_OR_HV_REQUIRED_ERROR
See suggested change above

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
Consider aggregating these functions in a `PylifeSignal` class. Then the validation if the `pd.Series` is complete can be centralized. The sanitize checks are now spread accross the whole module and they often do not properly raise but simply assert.

We can treat this in a separate issue.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +    if "R_m" in assessment_parameters:
Put those sanitize checks to the top of the function. Fail early.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +    assert "P_A" in assessment_parameters
Sanitize checks to the top of the function.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +def calculate_material_woehler_parameters_P_RAM(assessment_parameters_):
Please rename the argument to `assessment_parameters` or `assessment_prms` and then rename the local variable in the function from `assessment_parameters` to `prms`. Then the function will be way more readable.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/fkm_nonlinear/parameter_calculations.py
> +    assert result.success
Please raise instead of assert. Ideally with an error message. Give the user a chance to properly catch the exception.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/woehler_fkm_nonlinear.py
> +        #woehler_curve_minimum_lifetime._obj.P_RAM_Z_scalar = np.min(woehler_curve_minimum_lifetime._obj.P_RAM_Z_scalar)
Please drop commented code.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/strength/woehler_fkm_nonlinear.py
> +        assert self._obj.d_RAJ < 0, f"d_RAJ ({self._obj.d_RAJ}) has to be negative!"
Can the assertion actually fail? If so, raise a `ValueError` instead. An assertion must only fail if its a bug in the code that asserts.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/fkm_nonlinear.py
> +            if type(self._load) == pd.core.frame.DataFrame:
Use `isinstance()` (also in all the other places)

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/fkm_nonlinear.py
> +                return self._load.iloc[0].values[0]
Why can this be a `DataFrame` and why are we sure that always the first column is relevant? Wouldn't it be smarter to just always pass only the first column as a `np.ndarray` and then use `np.asarray()` to catch the single floats?

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/fkm_nonlinear.py
> +
Please avoid too nested `if ... else` trees

```suggestion
        while True:
            # iz = len(self._residuals)

            if iz == ir:
                previous_point = self._residuals[-1]

                # if the current load is a new maximum
                if np.abs(current_load_representative) > load_max_seen+1e-12:
                    # case a) i., "Memory 3"
                    current_point = self._handle_case_a_i(current_point, previous_point, largest_point, recording_lists,
                                                              current_load_representative, load_max_seen)
                    ir += 1

                else:
                    current_point = self._handle_case_a_ii(load_max_seen, current_load_representative, current_point, previous_point)

                break

            if iz < ir:
                # branch is fully part of the initial curve, case "Memory 1"
                current_point = self._handle_case_b(current_point)
                break

            previous_point_0 = self._residuals[-2]
            previous_point_1 = self._residuals[-1]

            # is the current load extent smaller than the last one?
            current_load_extent = np.abs(current_load_representative-previous_point_1.load_representative)
            previous_load_extent = np.abs(previous_point_1.load_representative-previous_point_0.load_representative)
            if current_load_extent < previous_load_extent-1e-12:
                current_point = self._handle_case_c_i(current_point, previous_point_0, previous_point_1)
                break

            # no -> we have a new hysteresis
            self._handle_case_c_ii(recording_lists, previous_point_0, previous_point_1)

            iz -= 2

            # if the points of the hysteresis lie fully inside the seen range of loads, i.e.,
            # the turn points are smaller than the maximum turn point so far
            # (this happens usually in the second run of the HCM algorithm)
            if np.abs(previous_point_0.load_representative) < load_max_seen-1e-12 and np.abs(previous_point_1.load_representative) < load_max_seen-1e-12:
                # case "Memory 2", "c) ii B"
                # the primary branch is not yet reached, continue processing residual loads, potentially
                # closing even more hysteresis

                self._hcm_message += ","

                # add a discontinuity marker
                self._hcm_point_history.append(("discontinuity", None, self._hysteresis_index))
                continue

            # case "Memory 1", "c) ii A"
            # The last hysteresis saw load values equal to the previous maximum.
            # (Higher values cannot happen here.)
            # The load curve follows again the primary path.
            # No further hystereses can be closed, continue with the next load value.
            # Previously, iz was decreased by 2 and will be increased by 1 at the end of this loop ,
            # effectively `iz = iz - 1` as described on p.70

            # Proceed on primary path for the rest, which was not part of the closed hysteresis
            current_point = self._proceed_on_primary_branch(current_point)

            # store strain values, this is for the FKM nonlinear roughness & surface layer algorithm, which adds residual stresses in another pass of the HCM algorithm
            self._strain_values.append(current_point.strain)

            # count number of strain values in the first run of the HCM algorithm
            if self._run_index == 1:
                self._n_strain_values_first_run += 1

            break


```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/fkm_nonlinear.py
> +    def _handle_secondary_branch(self, n_points_per_branch, only_hystereses, strain_values_primary, stress_values_primary,
We need to get rid of these positional parameters and replace them with something more readable

- [x] Please file issue after merge

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/fkm_nonlinear.py
> +        return np.array(strain_values_primary), np.array(stress_values_primary), np.array(hysteresis_index_primary), \
Do we really need to return those as individual values. Can't we put it into some `dict()` or dataclass or maybe even a `pd.DataFrame`? This seems really error prone.

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/fkm_nonlinear.py
> +                hcm_point = previous_point
Can't this loop be vectorized somehow?

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/fkm_nonlinear.py
> +            previous_point = hcm_point
At some point we need to refactor to reduce complexity.

Steps like this, for example.

```suggestion
        for (type, hcm_point, hysteresis_index) in old_hcm_point_history:
            if type != "primary":
                self._hcm_point_history.append((type, hcm_point, hysteresis_index))
                previous_point = hcm_point
                continue

            if previous_point.stress * hcm_point.stress < 0:
                sign = np.sign(hcm_point.stress)
                intermediate_point = FKMNonlinearDetector._HCM_Point(
                    strain=sign*largest_abs_strain, stress=sign*largest_abs_stress_seen
                )
                self._hcm_point_history.append(("secondary", intermediate_point, hysteresis_index))
                self._hcm_point_history.append(("primary", hcm_point, hysteresis_index))
            else:
                self._hcm_point_history.append((type, hcm_point, hysteresis_index))

            if abs(hcm_point.stress) > largest_abs_stress_seen:
                largest_abs_stress_seen = abs(hcm_point.stress)
                largest_abs_strain = abs(hcm_point.strain)

            previous_point = hcm_point


```

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/general.py
> +        return turn_index, selected_samples
Shouldn't this all go to `fkm_nonlinear.py`?

2023-09-18 16:26 UTC, johannes-mueller commented on src/pylife/stress/rainflow/recorders.py
> +        if len(self._S_min) > 0 and type(self._S_min[0]) == pd.core.series.Series:
This also can likely be simplified. 

- [ ] Please file issue about refactoring after the merge.

2023-09-18 16:26 UTC, johannes-mueller commented on tests/materiallaws/test_notch_approximation_law.py
> +        ])
Consider putting datasets like this into a separate file to make the test more readable.

Like for example https://github.com/boschresearch/pylife/blob/develop/tests/materialdata/woehler/data.py

2023-09-18 16:26 UTC, johannes-mueller commented on tests/mesh/test_gradient.py
> +    df = pd.DataFrame({'node_id':     [1, 2, 2, 3, 4, 4, 5, 5, 5, 5, 6, 6, 7, 8, 8, 9],
Where are all these whitespaces coming from? Please revert them.

2023-09-18 16:26 UTC, johannes-mueller commented on tests/mesh/test_gradient.py
> +def test_gradient_3D_dx():
Please add a test with the index levels flipped. 

Like this one: https://github.com/boschresearch/pylife/blob/a9fe148ef1b152215a798f683608aca1f095c940/tests/mesh/test_gradient.py#L63

2023-09-18 16:26 UTC, johannes-mueller commented on tests/stress/rainflow/test_find_turns.py
Please revert this change. There should be two blank lines between free functions according to PEP8

2023-10-13 16:47 UTC, maierbn commented
@johannes-mueller I addressed most of the comments and marked them as resolved. Some are not yet resolved, either where I would need your input again or where they contain an issue for after the merge.
I applied two suggestions directly in GitHub and I think they got committed without sign-off. Therefore I had to rebase, add the sign-offs and force push.

2023-11-02 16:17 UTC, maierbn commented
@johannes-mueller I fail to install it because of dependency problems:
```
pip install -e .[all]
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://anu9rng:****@rb-artifactory.bosch.com/artifactory/api/pypi/python-virtual/simple
Obtaining file:///home/mbe7rng/software/pylife
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement pandas!=2.1,>=1.4.0 (from pylife[all]) (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
ERROR: No matching distribution found for pandas!=2.1,>=1.4.0
```
Is the spec. of `numpy==1.23.5` really necessary?

2023-11-02 16:24 UTC, johannes-mueller commented
> ```
> 
> ```
> 
> 
>     
>   
> 
> Is the spec. of `numpy==1.23.5` really necessary?

It used to be necessary because numba had a problem with newer versions. Maybe they fixed it in the meantime and we can try to uplift the restriction.

I filed #39 in order to check.

2023-11-02 16:50 UTC, maierbn commented
Okay, seems like the numpy persion fix is required for now.. I now managed to install it with the restriction. 
Still the docs won't build, I tried the following:
```
python -m pip install -e .[docs]    # was missing jupyter, therefore I added:
python -m pip install -e .[extras]
```
Then in `docs` directory:
```
make html
```
Now it complains about `pandoc`: 
```
$ make html
Sphinx v7.2.6 in Verwendung
making output directory... erledigt
loading intersphinx inventory from http://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://docs.python.org/3.10/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/stable/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/scipy/reference/objects.inv...
loading intersphinx inventory from https://pyscaffold.org/en/stable/objects.inv...
intersphinx inventory has moved: http://www.sphinx-doc.org/en/master/objects.inv -> https://www.sphinx-doc.org/en/master/objects.inv
intersphinx inventory has moved: https://matplotlib.org/objects.inv -> https://matplotlib.org/stable/objects.inv
intersphinx inventory has moved: https://docs.scipy.org/doc/scipy/reference/objects.inv -> https://docs.scipy.org/doc/scipy/objects.inv
[autosummary] generating autosummary for: 3rd-party-licenses.md, CHANGELOG.md, CODINGSTYLE.rst, CONTRIBUTING.md, INSTALLATION.md, LICENSE.md, NEWS-2.0.md, NOTICE.md, README.md, broadcaster.rst, ..., tutorials.rst, tutorials/stress-strength.rst, user_guide.rst, utils/functions.rst, utils/histogram.rst, utils/probability_data.rst, variable_names.rst, vmap/vmap.rst, vmap/vmap_export.rst, vmap/vmap_import.rst
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
myst v2.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 79 source files that are out of date
updating environment: [new config] 79 added, 0 changed, 0 removed
executing broadcaster13%] broadcaster
reading sources... [ 16%] demos/hotspot_beam
Notebook error:
PandocMissing in demos/hotspot_beam.nblink:
Pandoc wasn't found.
Please check that pandoc is installed:
https://pandoc.org/installing.html
Makefile:29: recipe for target 'html' failed
make: *** [html] Error 2
```
Installing it `python -m pip install pandoc` does not change anything. How is the documentation normally build? Maybe could we add a Github Action to check if it builds?

2023-11-02 16:54 UTC, johannes-mueller commented
> How is the documentation normally build? Maybe could we add a Github Action to check if it builds?

It is normally built by readthedocs fetching the repo and build it. A github action to check if it builds sure would be a good thing, although it might not guarantee that it builds on readthedocs. I will look into this tomorrow.

2023-11-22 10:41 UTC, johannes-mueller commented
> Installing it `python -m pip install pandoc` does not change anything. How is the documentation normally build? Maybe could we add a Github Action to check if it builds?

You actually need to install the `pandoc` software itself on your host system. The `pandoc` package from PyPi is only the python bindings for.

In the meantime I merged #39 and #40 to `develop`. Can you please merge `develop` to trigger the renewed CI?

2023-11-22 15:47 UTC, maierbn commented
I merged develop and fixed the documentation build.

2023-11-28 14:01 UTC, johannes-mueller approved these changes

2023-11-28 14:16 UTC, closed without merging

2023-11-28 14:16 UTC, johannes-mueller commented
Squashed manually, thanks.

2023-12-05 15:39 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +
@maierbn Is this resolved? Is it correct that `K()` sets `K_prime` and vice verca?