48 simplify notch approximation lawbinned
boschresearch/pylife pull request #60
Opened 2023-12-21 11:03 UTC by maierbn

2024-01-16 15:16 UTC, johannes-mueller requested changes
Quite an improvement, thanks. Please take a look at the one comment in the code.

2024-01-16 15:16 UTC, johannes-mueller commented on src/pylife/materiallaws/notch_approximation_law.py
> +                                f" but a higher absolute load value of |{load.max()}| is requested (in stress()).")
Maybe we can `._find_load_index_or_raise(load)` which finds the `index` of the load or raises if any of them is outside. Would remove code duplication and help readability.

Or at least introduce a method `._raise_if_requested_load_higher_than_max_abs_load(index, max_abs_load, max_load)`

2024-01-26 14:00 UTC, johannes-mueller commented
We should merge #67 ASAP to get the CI working again

2024-01-26 14:56 UTC, johannes-mueller approved these changes
Squash?

2024-01-26 14:56 UTC, maierbn commented
I forgot the Sign-off again. Does it gets fixed with a squash? Then yes, please :-)

2024-01-26 14:58 UTC, merged

2024-01-26 14:59 UTC, johannes-mueller commented
Ok, thanks.